### ISSUE TITLE
No need for 1 goroutine per core

### ISSUE THREAD

**Issue by mgilbir** [thanasisk/delaporter#4]
You are currently limiting the performance by allowing one goroutine per core, you can increase the number of goroutines you are creating by changing [line 85 of delaporter.go](https://github.com/thanasisk/delaporter/blob/master/delaporter.go#L85)

For an example of the performance difference take a look at the [charts in this post](http://www.dmuth.org/node/1414/multi-core-cpu-performance-google-go)

**Comment by thanasisk** [comment]
thank you for the issue! Is there a rule of thumb, so to speak, about how many workers I should start up?
2xworkers, 4xworkers, how many?
thanks again for the issue - I will take care of it later today.

**Comment by mgilbir** [comment]
Not that I'm aware of. 
I normally end up tuning it by trial and error but think of goroutines as something "cheap". 

In this case I'd try with 100 and 1000 and take it from there based on what you see.

**Comment by thanasisk** [comment]
I introduced a new command line argument "factor" which can be used to allow more goroutines per core and updated documentation. Thanks for the feedback.
